//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Db.Isms.Table.Old
{
    using System;
    using System.Collections.Generic;
    
    public class atsdata
    {
        public int ID { get; set; }
        public string RequisitionNo { get; set; }
        public string ActionNo { get; set; }
        public string MSISDN { get; set; }
        public string KITNumber { get; set; }
        public string HasActivated { get; set; }
        public string ATSTicketNo { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
    }
}
