//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Db.Isms.Table.Old
{
    using System;
    using System.Collections.Generic;
    
    public  class imsitype
    {
        public imsitype()
        {
            //this.newtestsimrequisitionlines = new HashSet<newtestsimrequisitionline>();
        }
    
        public int IMSITypeID { get; set; }                         /*Id*/
        public string Name { get; set; }
        public bool Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        //public virtual ICollection<newtestsimrequisitionline> newtestsimrequisitionlines { get; set; }
    }
}
